In [1]:
from sklearn import preprocessing
import numpy as np
import pandas as pd
import random
from sklearn.model_selection import train_test_split
from math import exp

In [2]:
df = pd.read_csv('insurance_data.csv')
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [3]:
sx = preprocessing.MinMaxScaler()
sy = preprocessing.MinMaxScaler()


In [4]:
df.shape[0]

28

In [5]:
scaled_x = sx.fit_transform(df.drop('bought_insurance', axis = 'columns'))
scaled_x

array([[0.09090909, 1.        ],
       [0.15909091, 0.        ],
       [0.65909091, 1.        ],
       [0.77272727, 0.        ],
       [0.63636364, 1.        ],
       [0.86363636, 1.        ],
       [0.84090909, 0.        ],
       [0.95454545, 0.        ],
       [1.        , 1.        ],
       [0.97727273, 1.        ],
       [0.        , 1.        ],
       [0.22727273, 1.        ],
       [0.20454545, 0.        ],
       [0.25      , 0.        ],
       [0.70454545, 1.        ],
       [0.84090909, 1.        ],
       [0.15909091, 0.        ],
       [0.90909091, 1.        ],
       [0.02272727, 0.        ],
       [0.        , 1.        ],
       [0.06818182, 1.        ],
       [0.18181818, 0.        ],
       [0.5       , 1.        ],
       [0.61363636, 1.        ],
       [0.72727273, 1.        ],
       [0.81818182, 1.        ],
       [0.11363636, 1.        ],
       [0.63636364, 1.        ]])

In [6]:
scaled_y = sy.fit_transform(df['bought_insurance'].values.reshape(df.shape[0],1))
scaled_y.shape[0]

28

In [7]:
scaled_y.reshape(28,)

array([0., 0., 1., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1.,
       1., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0.])

In [8]:
scaled_x[0][0]

np.float64(0.09090909090909088)

In [9]:
x_train ,x_test, y_train, y_test = train_test_split(scaled_x,scaled_y, test_size = 0.2, random_state = 42)


In [10]:
size = x_train.shape[0]

In [29]:
def sig_func(a):
    return 1/(1+np.exp(-a))

In [30]:
def sgdd(x,y,epochs,lr):
    w1=w2=1
    bias = 0
    for i in range(epochs):
        idx = random.randint(0,size-1)
        ws = w1 * x[idx][0] + w2 * x[idx][1] + bias
        ws = np.squeeze(ws)
        y_pred = sig_func(ws)
        cost = (y[idx] - y_pred)**2
        w1d = -2 * (y[idx] - y_pred)*x[idx][0]
        w2d = -2 * (y[idx] - y_pred)* x[idx][1]
        bd = -2 * (y[idx] - y_pred)
        w1 = w1 - lr * w1d
        w2 = w2 - lr*w2d
        bias = bias - lr*bd
    return cost,w1,w2,bias
    
    

In [31]:
cost,w1,w2,bias = sgdd(x_train,y_train,500,0.01)
cost,w1,w2,bias

(array([0.46295344]),
 array([1.27664976]),
 array([0.64714081]),
 array([-0.94479282]))

In [32]:
y_test.shape

(6, 1)

In [33]:
azz = w1 * scaled_x[22][0] + w2 * scaled_x[22][1] + bias
y_predicted = sig_func(azz)
scaled_y[22]


array([1.])

In [37]:
print('1') if y_predicted >= 0.5 else print('0')


1


In [35]:
w1

array([1.27664976])